service:
  kind: Service
  apiVersion: v1
  metadata:
    name: gloriglobalsukses-admin
  spec:
    selector:
      app: gloriglobalsukses-admin
    ports:
      - protocol: TCP
        port: 3000
        targetPort: 80
        name: http-gloriglobalsukses-admin
    type: NodePort
deployment:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: gloriglobalsukses-admin
    labels:
      app: gloriglobalsukses-admin
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: gloriglobalsukses-admin
    template:
      metadata:
        labels:
          app: gloriglobalsukses-admin
      spec:
        containers: 
        - name: gloriglobalsukses-admin
          image: '{DOCKER_IMAGE_URI}'
          ports:
            - containerPort: 80
        imagePullSecrets:
          - name: regcred
